#!/bin/sh

set -e

redoak_src_datadir="$(dirname $(readlink -m "$0"))/data"
cabal build "$@"
if [ -n "$NIX_GHCJS" ]; then
  for jsexe in dist/build/*/*.jsexe; do
    cp -r "$redoak_src_datadir"/* $jsexe
  done
fi
